apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diploma-platform.fullname" . }}-init-scripts
  labels:
    {{- include "diploma-platform.labels" . | nindent 4 }}
data:
  clickhouse-init.sql: |
{{ .Files.Get "files/clickhouse-init.sql" | indent 4 }}
  02-core-schema.sql: |
{{ .Files.Get "files/02-core-schema.sql" | indent 4 }}
  03-analysis-schema.sql: |
{{ .Files.Get "files/03-analysis-schema.sql" | indent 4 }}
