apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diploma-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fortech4N9/infra.git
    targetRevision: main
    path: helm/diploma-platform
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: diploma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
