apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diploma-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Fortech4N9/infra.git
    targetRevision: main
    path: argocd/apps
    directory:
      include: "{platform,infrastructure}.yaml"
      exclude: "root-app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
